# Generated by Django 4.2.26 on 2025-11-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_license', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('vehicletype_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('seats_num', models.IntegerField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('plate', models.CharField(max_length=30, unique=True)),
                ('vehicletype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reservation_date', models.DateField()),
                ('availability_status', models.CharField(blank=True, max_length=30, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('charge_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.rental')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('insurance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('coverage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental.vehicle')),
            ],
        ),
    ]
